-- MySQL Script generated by MySQL Workbench
-- 06/17/15 22:23:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eCareIS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eCareIS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eCareIS` DEFAULT CHARACTER SET utf8 ;
USE `eCareIS` ;

-- -----------------------------------------------------
-- Table `eCareIS`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`option` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`option` (
  `option_id` INT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `monthly_cost` INT NULL,
  `activation_charge` INT NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`user` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`user` (
  `user_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NULL,
  `lastname` VARCHAR(40) NULL,
  `birthday` DATE NULL,
  `passport` VARCHAR(120) NULL,
  `address` VARCHAR(120) NULL,
  `email` VARCHAR(80) NULL,
  `password` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`inconsistent_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`inconsistent_option` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`inconsistent_option` (
  `id` INT NULL AUTO_INCREMENT,
  `src_option_id` INT NULL,
  `inconsistent_option_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`dependent_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`dependent_option` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`dependent_option` (
  `id` INT NULL AUTO_INCREMENT,
  `src_option_id` INT NULL,
  `dependent_option_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`tariff_possible_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`tariff_possible_option` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`tariff_possible_option` (
  `id` INT NULL AUTO_INCREMENT,
  `tariff_id` INT NULL,
  `possible_option_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`contract` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`contract` (
  `contract_id` INT NULL AUTO_INCREMENT,
  `phone_number` MEDIUMTEXT NULL,
  `tariff_id` INT NULL,
  `client_id` INT NULL,
  `blocked` TINYINT(1) NULL,
  `blocked_by_staff` TINYINT(1) NULL,
  PRIMARY KEY (`contract_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`contract_chosen_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`contract_chosen_option` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`contract_chosen_option` (
  `id` INT NULL AUTO_INCREMENT,
  `contract_id` INT NULL,
  `chosen_option_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCareIS`.`tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eCareIS`.`tariff` ;

CREATE TABLE IF NOT EXISTS `eCareIS`.`tariff` (
  `tariff_id` INT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`tariff_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
